sudo: required
language: java
jdk:
- oraclejdk7

install: true



env: JAVA_OPTS="-Djava.library.path=lib/native_libraries/linux-amd64"

script:
- export MAVEN_OPTS="-Djava.library.path=lib/native_libraries/linux-amd64"
- mvn -q clean install -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true
